name: manage-azure-policy-7cea0bc2
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'vipulCIS1.4/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.4.0_c3f5c4d9-9a1d-4a99-85c0-7f93e384d5c5/**'
#      - .github/workflows/manage-azure-policy-7cea0bc2.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_7cea0bc2}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          vipulCIS1.4/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_v1.4.0_c3f5c4d9-9a1d-4a99-85c0-7f93e384d5c5/**
